import '@/styles/globals.css'
import type { Metadata } from 'next'
import { Inter, Poppins, Roboto } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
const roboto = Roboto({
  subsets: ['latin'],
  weight: '400'
})

export const metadata: Metadata = {
  title: 'Manager Worker',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={`${roboto.className} dark:bg-zinc-700`}>{children}</body>
    </html>
  )
}
